### This file is part of 'LEAVcore' package for R.

### Copyright (C) 2024-2026, ICAR-NBPGR.
#
# LEAVcore is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# LEAVcore is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
#  A copy of the GNU General Public License is available at
#  https://www.r-project.org/Licenses/

#' Generate Core collections with Length of Encoded Attribute Values
#'
#' Based on Length of Encoded Attribute Values (LEAV)
#' \insertCite{wallace_information_1968,balakrishnan_Strategies_2001,balakrishnan_Strategies_2001a,balakrishnan_Strategies_2003}{LEAVcore}
#' estimated from qualitative and/or quantitative trait data, core collections
#' can be generated by the three following methods. \describe{
#' \item{Method I}{Classification based on pre-determined diversity represented
#' by LEAV estimates implemented in \code{LEAVcore1}.}
#' \item{Method II}{Purposive selection of  accessions with highest rank of
#' LEAV estimates implemented in \code{LEAVcore2}.}
#' \item{Method III}{Stratified sampling of accessions from diversity
#' groups/strata computed from LEAV estimates partially implemented in
#' \code{LEAVcore3}.}
#' }.
#' \loadmathjax
#'
#' \insertCite{balakrishnan_Strategies_2001,balakrishnan_Strategies_2001a;textual}{LEAVcore}
#' describe three different methods of constructing core collections from
#' estimates of Length of Encoded Attribute Values.
#'
#'  \subsection{Method I: Classification based on pre-determined diversity represented
#'  by LEAV estimates}{
#'
#'  }
#'
#'  \subsection{Method II: Purposive selection of  accessions with highest rank of
#' LEAV estimates}{
#'
#'  }
#'
#'  \subsection{Method III: Stratified sampling of accessions from diversity
#' groups/strata computed from LEAV estimates}{
#'
#'  }
#'
#' @inheritParams LEAV data names quantitative qualitative e
#' @param size The desired core set size proportion.
#' @param prop.adj The method for relative frequency transformation for
#'   qualitative traits. Either \code{"none"} for no transformation or
#'   \code{"log"} for log-frequency transformation or \code{"sqrt"} for square
#'   root-proportion transformation (see \code{\link[LEAVcore]{prop.adj}}).
#'
#' @returns
#'
#' @name LEAVcore_functions
#' @rdname LEAVcore_functions
#'
#' @importFrom grDevices nclass.Sturges
#' @importFrom stats approxfun density sd
#' @importFrom stratification strata.cumrootf
#'
#'
#' @examples
NULL

# Method I : ----
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' @rdname LEAVcore_functions
#' @export
LEAVcore1 <- function(data, names,
                     quantitative = NULL, qualitative = NULL,
                     size, prop.adj = c("none", "log", "sqrt"),
                     e) {

  prop.adj <- match.arg(prop.adj)

  # check if 'size' argument is numeric vector of unit length
  if (!is.null(size)) {
    if (!(is.numeric(size) && length(size) == 1)) {
      stop('"size" should be a numeric vector of unit length.')
    }
  }

  # check if 'size' is a proportion between 0 and 1
  if (size <= 0 || size >= 1) {
    stop('"size" should be a proportion between 0 and 1.')
  }

  N <- nrow(data)
  size.count <- ceiling(size * N)

  ## Find freq for qualitative traits ----

  # Core group
  freq1 <- lapply(qualitative, function(x) {
    prop <-  prop.adj(data[, x], method = prop.adj)
    fqout <- prop * size.count
    fq_overall <- summary(data[, x])
    fqout <- ifelse(fqout > fq_overall, fq_overall, fqout)
    fqout <- round_preserve_sum(fqout)
    return(fqout)
  })
  names(freq1) <- qualitative

  # Non-Core group
  freq2 <- lapply(qualitative, function(x) {
    summary(data[, x]) - freq1[[x]]
  })
  names(freq2) <- qualitative


  ## Find mean and variance for quantitative traits ----

  # Core group
  # mean1 and sd1: From kernel density of size = size.count
  stat1 <- lapply(quantitative, function(x) {
    dens.obs <- density(data[,x], kernel = "gaussian", n = size.count)
    dens.fun <- approxfun(dens.obs)

    smpl <- sample(data[,x], size = size.count, replace = FALSE,
                   prob = dens.fun(data[,x]))

    out <- data.frame(mean = mean(smpl), sd = sd(smpl))

    return(out)
  })
  names(stat1) <- quantitative

  # Non-Core group
  # mean2 and sd2: From overall
  stat2 <- lapply(quantitative, function(x) {
    out <- data.frame(mean = mean(data[,x]), sd = sd(data[,x]))
    return(out)
  })
  names(stat2) <- quantitative

  mean1 <- unlist(lapply(stat1, function(x) { x[, "mean"] }))
  sd1 <- unlist(lapply(stat1, function(x) { x[, "sd"] }))
  mean2 <- unlist(lapply(stat2, function(x) { x[, "mean"] }))
  sd2 <- unlist(lapply(stat2, function(x) { x[, "sd"] }))

  ## Estimate LEAVs ----

  # For Core
  LEAVdf1 <- LEAV(data = data, names = names,
                  quantitative = quantitative, qualitative = qualitative,
                  freq = freq1, mean = mean1, sd = sd1, e = e)

  # For Non-Core
  LEAVdf2 <- LEAV(data = data, names = names,
                  quantitative = quantitative, qualitative = qualitative,
                  freq = freq2, mean = mean2, sd = sd2, e = e)

  core_ind <- LEAVdf1$LEAV <= LEAVdf2$LEAV

  ## Correction ----
  ## When core size exceeds size.count

  if (sum(core_ind) > size.count) {
    coredf <- LEAVdf1[core_ind, ]
    coredf <- sort_by(coredf, coredf$LEAV, decreasing = TRUE)
    core <- coredf[1:size.count, names]
  } else {
    core <- LEAVdf1[core_ind, names]
  }

  return(core)

}

# Method II : ----
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' @rdname LEAVcore_functions
#' @export
LEAVcore2 <- function(data, names,
                      quantitative = NULL, qualitative = NULL,
                      size, prop.adj = c("none", "log", "sqrt"),
                      e) {

  prop.adj <- match.arg(prop.adj)

  # check if 'size' argument is numeric vector of unit length
  if (!is.null(size)) {
    if (!(is.numeric(size) && length(size) == 1)) {
      stop('"size" should be a numeric vector of unit length.')
    }
  }

  # check if 'size' is a proportion between 0 and 1
  if (size <= 0 || size >= 1) {
    stop('"size" should be a proportion between 0 and 1.')
  }

  N <- nrow(data)
  size.count <- ceiling(size * N)

  ## Find freq for qualitative traits ----
  freq <- lapply(qualitative, function(x) {
    prop <-  prop.adj(data[, x], method = prop.adj)
    fqout <- prop * nrow(data)
    # fqout <- round_preserve_sum(fqout)
    return(fqout)
  })
  names(freq) <- qualitative

  ## Find mean and variance for quantitative traits ----

  stat <- lapply(quantitative, function(x) {
    out <- data.frame(mean = mean(data[,x]), sd = sd(data[,x]))
    return(out)
  })
  names(stat) <- quantitative

  mean <- unlist(lapply(stat, function(x) { x[, "mean"] }))
  sd <- unlist(lapply(stat, function(x) { x[, "sd"] }))

  ## Estimate LEAV ----
  LEAVdf <- LEAV(data = data, names = names,
                 quantitative = quantitative,
                 qualitative = qualitative,
                 adj = FALSE,
                 freq = freq, mean = mean, sd = sd, e = e)

  LEAVdf <- sort_by(LEAVdf, LEAVdf$LEAV, decreasing = TRUE)

}

# Method III : ----
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' @rdname LEAVcore_functions
#' @export
LEAVcore3 <- function(data, names,
                     quantitative = NULL, qualitative = NULL,
                     size, prop.adj = c("none", "log", "sqrt"),
                     e) {

  prop.adj <- match.arg(prop.adj)

  # check if 'size' argument is numeric vector of unit length
  if (!is.null(size)) {
    if (!(is.numeric(size) && length(size) == 1)) {
      stop('"size" should be a numeric vector of unit length.')
    }
  }

  # check if 'size' is a proportion between 0 and 1
  if (size <= 0 || size >= 1) {
    stop('"size" should be a proportion between 0 and 1.')
  }

  N <- nrow(data)
  size.count <- ceiling(size * N)

  ## Find freq for qualitative traits ----
  freq <- lapply(qualitative, function(x) {
    prop <-  prop.adj(data[, x], method = prop.adj)
    fqout <- prop * nrow(data)
    # fqout <- round_preserve_sum(fqout)
    return(fqout)
  })
  names(freq) <- qualitative

  ## Find mean and variance for quantitative traits ----

  stat <- lapply(quantitative, function(x) {
    out <- data.frame(mean = mean(data[,x]), sd = sd(data[,x]))
    return(out)
  })
  names(stat) <- quantitative

  mean <- unlist(lapply(stat, function(x) { x[, "mean"] }))
  sd <- unlist(lapply(stat, function(x) { x[, "sd"] }))

  ## Estimate LEAV ----
  LEAVdf <- LEAV(data = data, names = names,
                 quantitative = quantitative,
                 qualitative = qualitative,
                 adj = FALSE,
                 freq = freq, mean = mean, sd = sd, e = e)

  LEAVdf <- sort_by(LEAVdf, LEAVdf$LEAV, decreasing = TRUE)

  ## Find the strata boundaries ----
  nStrata <- nclass.Sturges(LEAVdf$LEAV)
  # Use method by Dalenius and Hodges (1959)
  strat_out <-
    stratification::strata.cumrootf(x = LEAVdf$LEAV,
                                    n = size.count,
                                    Ls = nStrata,
                                    nclass = nStrata*15) # see Details

  LEAVdf$LEAVStrata <-  strat_out$stratumID

  return(LEAVdf)

}
